'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
'
Namespace PublicationOutput25
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="PublicationOutput25Soap", [Namespace]:="urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5")>  _
    Partial Public Class PublicationOutput25
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ReleaseOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ReleaseByIshLngRefOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetMetaDataByIshLngRefOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetMetaDataOperationCompleted As System.Threading.SendOrPostCallback
        
        Private FindOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RetrieveMetadataOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RetrieveVersionMetadataOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RetrieveMetadataByIshLngRefsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetDataObjectInfoByIshLngRefOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetNextDataObjectChunkByIshLngRefOperationCompleted As System.Threading.SendOrPostCallback
        
        Private FolderLocationOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ContainingOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UsingBaselineOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Esri_Trisoft_TopicStatus_Tool.My.MySettings.Default.Esri_Trisoft_TopicStatus_Tool_PublicationOutput25_PublicationOutput25
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ReleaseCompleted As ReleaseCompletedEventHandler
        
        '''<remarks/>
        Public Event ReleaseByIshLngRefCompleted As ReleaseByIshLngRefCompletedEventHandler
        
        '''<remarks/>
        Public Event GetMetaDataByIshLngRefCompleted As GetMetaDataByIshLngRefCompletedEventHandler
        
        '''<remarks/>
        Public Event GetMetaDataCompleted As GetMetaDataCompletedEventHandler
        
        '''<remarks/>
        Public Event FindCompleted As FindCompletedEventHandler
        
        '''<remarks/>
        Public Event RetrieveMetadataCompleted As RetrieveMetadataCompletedEventHandler
        
        '''<remarks/>
        Public Event RetrieveVersionMetadataCompleted As RetrieveVersionMetadataCompletedEventHandler
        
        '''<remarks/>
        Public Event RetrieveMetadataByIshLngRefsCompleted As RetrieveMetadataByIshLngRefsCompletedEventHandler
        
        '''<remarks/>
        Public Event GetDataObjectInfoByIshLngRefCompleted As GetDataObjectInfoByIshLngRefCompletedEventHandler
        
        '''<remarks/>
        Public Event GetNextDataObjectChunkByIshLngRefCompleted As GetNextDataObjectChunkByIshLngRefCompletedEventHandler
        
        '''<remarks/>
        Public Event FolderLocationCompleted As FolderLocationCompletedEventHandler
        
        '''<remarks/>
        Public Event ContainingCompleted As ContainingCompletedEventHandler
        
        '''<remarks/>
        Public Event UsingBaselineCompleted As UsingBaselineCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5/Release", RequestNamespace:="urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5", ResponseNamespace:="urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Release(ByRef psAuthContext As String, ByVal psLogicalId As String, ByVal psVersion As String, ByVal psOutputFormat As String, ByVal psLngCombination As String, ByRef psOutXMLBaselineFreezeReport As String, ByRef pbOutIsFrozen As Boolean) As String
            Dim results() As Object = Me.Invoke("Release", New Object() {psAuthContext, psLogicalId, psVersion, psOutputFormat, psLngCombination, psOutXMLBaselineFreezeReport, pbOutIsFrozen})
            psAuthContext = CType(results(1),String)
            psOutXMLBaselineFreezeReport = CType(results(2),String)
            pbOutIsFrozen = CType(results(3),Boolean)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReleaseAsync(ByVal psAuthContext As String, ByVal psLogicalId As String, ByVal psVersion As String, ByVal psOutputFormat As String, ByVal psLngCombination As String, ByVal psOutXMLBaselineFreezeReport As String, ByVal pbOutIsFrozen As Boolean)
            Me.ReleaseAsync(psAuthContext, psLogicalId, psVersion, psOutputFormat, psLngCombination, psOutXMLBaselineFreezeReport, pbOutIsFrozen, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReleaseAsync(ByVal psAuthContext As String, ByVal psLogicalId As String, ByVal psVersion As String, ByVal psOutputFormat As String, ByVal psLngCombination As String, ByVal psOutXMLBaselineFreezeReport As String, ByVal pbOutIsFrozen As Boolean, ByVal userState As Object)
            If (Me.ReleaseOperationCompleted Is Nothing) Then
                Me.ReleaseOperationCompleted = AddressOf Me.OnReleaseOperationCompleted
            End If
            Me.InvokeAsync("Release", New Object() {psAuthContext, psLogicalId, psVersion, psOutputFormat, psLngCombination, psOutXMLBaselineFreezeReport, pbOutIsFrozen}, Me.ReleaseOperationCompleted, userState)
        End Sub
        
        Private Sub OnReleaseOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReleaseCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReleaseCompleted(Me, New ReleaseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5/ReleaseByIshLngRef", RequestNamespace:="urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5", ResponseNamespace:="urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReleaseByIshLngRef(ByRef psAuthContext As String, ByVal plLngRef As Long, ByRef psOutXMLBaselineFreezeReport As String, ByRef pbOutIsFrozen As Boolean) As String
            Dim results() As Object = Me.Invoke("ReleaseByIshLngRef", New Object() {psAuthContext, plLngRef, psOutXMLBaselineFreezeReport, pbOutIsFrozen})
            psAuthContext = CType(results(1),String)
            psOutXMLBaselineFreezeReport = CType(results(2),String)
            pbOutIsFrozen = CType(results(3),Boolean)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReleaseByIshLngRefAsync(ByVal psAuthContext As String, ByVal plLngRef As Long, ByVal psOutXMLBaselineFreezeReport As String, ByVal pbOutIsFrozen As Boolean)
            Me.ReleaseByIshLngRefAsync(psAuthContext, plLngRef, psOutXMLBaselineFreezeReport, pbOutIsFrozen, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReleaseByIshLngRefAsync(ByVal psAuthContext As String, ByVal plLngRef As Long, ByVal psOutXMLBaselineFreezeReport As String, ByVal pbOutIsFrozen As Boolean, ByVal userState As Object)
            If (Me.ReleaseByIshLngRefOperationCompleted Is Nothing) Then
                Me.ReleaseByIshLngRefOperationCompleted = AddressOf Me.OnReleaseByIshLngRefOperationCompleted
            End If
            Me.InvokeAsync("ReleaseByIshLngRef", New Object() {psAuthContext, plLngRef, psOutXMLBaselineFreezeReport, pbOutIsFrozen}, Me.ReleaseByIshLngRefOperationCompleted, userState)
        End Sub
        
        Private Sub OnReleaseByIshLngRefOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReleaseByIshLngRefCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReleaseByIshLngRefCompleted(Me, New ReleaseByIshLngRefCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5/GetMetaDataByIshLngRef"& _ 
            "", RequestNamespace:="urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5", ResponseNamespace:="urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetMetaDataByIshLngRef(ByRef psAuthContext As String, ByVal plLngRef As Long, ByVal psXMLRequestedMetaData As String, ByRef psOutXMLObjList As String) As String
            Dim results() As Object = Me.Invoke("GetMetaDataByIshLngRef", New Object() {psAuthContext, plLngRef, psXMLRequestedMetaData, psOutXMLObjList})
            psAuthContext = CType(results(1),String)
            psOutXMLObjList = CType(results(2),String)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetMetaDataByIshLngRefAsync(ByVal psAuthContext As String, ByVal plLngRef As Long, ByVal psXMLRequestedMetaData As String, ByVal psOutXMLObjList As String)
            Me.GetMetaDataByIshLngRefAsync(psAuthContext, plLngRef, psXMLRequestedMetaData, psOutXMLObjList, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetMetaDataByIshLngRefAsync(ByVal psAuthContext As String, ByVal plLngRef As Long, ByVal psXMLRequestedMetaData As String, ByVal psOutXMLObjList As String, ByVal userState As Object)
            If (Me.GetMetaDataByIshLngRefOperationCompleted Is Nothing) Then
                Me.GetMetaDataByIshLngRefOperationCompleted = AddressOf Me.OnGetMetaDataByIshLngRefOperationCompleted
            End If
            Me.InvokeAsync("GetMetaDataByIshLngRef", New Object() {psAuthContext, plLngRef, psXMLRequestedMetaData, psOutXMLObjList}, Me.GetMetaDataByIshLngRefOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetMetaDataByIshLngRefOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetMetaDataByIshLngRefCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetMetaDataByIshLngRefCompleted(Me, New GetMetaDataByIshLngRefCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5/GetMetaData", RequestNamespace:="urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5", ResponseNamespace:="urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetMetaData(ByRef psAuthContext As String, ByVal psLogicalId As String, ByRef psVersion As String, ByVal psOutputFormat As String, ByVal psLanguageCombination As String, ByVal psXMLRequestedMetaData As String, ByRef psOutXMLObjList As String) As String
            Dim results() As Object = Me.Invoke("GetMetaData", New Object() {psAuthContext, psLogicalId, psVersion, psOutputFormat, psLanguageCombination, psXMLRequestedMetaData, psOutXMLObjList})
            psAuthContext = CType(results(1),String)
            psVersion = CType(results(2),String)
            psOutXMLObjList = CType(results(3),String)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetMetaDataAsync(ByVal psAuthContext As String, ByVal psLogicalId As String, ByVal psVersion As String, ByVal psOutputFormat As String, ByVal psLanguageCombination As String, ByVal psXMLRequestedMetaData As String, ByVal psOutXMLObjList As String)
            Me.GetMetaDataAsync(psAuthContext, psLogicalId, psVersion, psOutputFormat, psLanguageCombination, psXMLRequestedMetaData, psOutXMLObjList, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetMetaDataAsync(ByVal psAuthContext As String, ByVal psLogicalId As String, ByVal psVersion As String, ByVal psOutputFormat As String, ByVal psLanguageCombination As String, ByVal psXMLRequestedMetaData As String, ByVal psOutXMLObjList As String, ByVal userState As Object)
            If (Me.GetMetaDataOperationCompleted Is Nothing) Then
                Me.GetMetaDataOperationCompleted = AddressOf Me.OnGetMetaDataOperationCompleted
            End If
            Me.InvokeAsync("GetMetaData", New Object() {psAuthContext, psLogicalId, psVersion, psOutputFormat, psLanguageCombination, psXMLRequestedMetaData, psOutXMLObjList}, Me.GetMetaDataOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetMetaDataOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetMetaDataCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetMetaDataCompleted(Me, New GetMetaDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5/Find", RequestNamespace:="urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5", ResponseNamespace:="urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Find(ByRef psAuthContext As String, ByVal peStatusFilter As eISHStatusgroup, ByVal psXMLMetadataFilter As String, ByVal psXMLRequestedMetadata As String, ByRef psOutXMLObjList As String) As String
            Dim results() As Object = Me.Invoke("Find", New Object() {psAuthContext, peStatusFilter, psXMLMetadataFilter, psXMLRequestedMetadata, psOutXMLObjList})
            psAuthContext = CType(results(1),String)
            psOutXMLObjList = CType(results(2),String)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub FindAsync(ByVal psAuthContext As String, ByVal peStatusFilter As eISHStatusgroup, ByVal psXMLMetadataFilter As String, ByVal psXMLRequestedMetadata As String, ByVal psOutXMLObjList As String)
            Me.FindAsync(psAuthContext, peStatusFilter, psXMLMetadataFilter, psXMLRequestedMetadata, psOutXMLObjList, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub FindAsync(ByVal psAuthContext As String, ByVal peStatusFilter As eISHStatusgroup, ByVal psXMLMetadataFilter As String, ByVal psXMLRequestedMetadata As String, ByVal psOutXMLObjList As String, ByVal userState As Object)
            If (Me.FindOperationCompleted Is Nothing) Then
                Me.FindOperationCompleted = AddressOf Me.OnFindOperationCompleted
            End If
            Me.InvokeAsync("Find", New Object() {psAuthContext, peStatusFilter, psXMLMetadataFilter, psXMLRequestedMetadata, psOutXMLObjList}, Me.FindOperationCompleted, userState)
        End Sub
        
        Private Sub OnFindOperationCompleted(ByVal arg As Object)
            If (Not (Me.FindCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent FindCompleted(Me, New FindCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5/RetrieveMetadata", RequestNamespace:="urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5", ResponseNamespace:="urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RetrieveMetadata(ByRef psAuthContext As String, ByVal pasLogicalIds() As String, ByVal peStatusFilter As eISHStatusgroup, ByVal psXMLMetadataFilter As String, ByVal psXMLRequestedMetadata As String, ByRef psOutXMLObjList As String) As String
            Dim results() As Object = Me.Invoke("RetrieveMetadata", New Object() {psAuthContext, pasLogicalIds, peStatusFilter, psXMLMetadataFilter, psXMLRequestedMetadata, psOutXMLObjList})
            psAuthContext = CType(results(1),String)
            psOutXMLObjList = CType(results(2),String)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RetrieveMetadataAsync(ByVal psAuthContext As String, ByVal pasLogicalIds() As String, ByVal peStatusFilter As eISHStatusgroup, ByVal psXMLMetadataFilter As String, ByVal psXMLRequestedMetadata As String, ByVal psOutXMLObjList As String)
            Me.RetrieveMetadataAsync(psAuthContext, pasLogicalIds, peStatusFilter, psXMLMetadataFilter, psXMLRequestedMetadata, psOutXMLObjList, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RetrieveMetadataAsync(ByVal psAuthContext As String, ByVal pasLogicalIds() As String, ByVal peStatusFilter As eISHStatusgroup, ByVal psXMLMetadataFilter As String, ByVal psXMLRequestedMetadata As String, ByVal psOutXMLObjList As String, ByVal userState As Object)
            If (Me.RetrieveMetadataOperationCompleted Is Nothing) Then
                Me.RetrieveMetadataOperationCompleted = AddressOf Me.OnRetrieveMetadataOperationCompleted
            End If
            Me.InvokeAsync("RetrieveMetadata", New Object() {psAuthContext, pasLogicalIds, peStatusFilter, psXMLMetadataFilter, psXMLRequestedMetadata, psOutXMLObjList}, Me.RetrieveMetadataOperationCompleted, userState)
        End Sub
        
        Private Sub OnRetrieveMetadataOperationCompleted(ByVal arg As Object)
            If (Not (Me.RetrieveMetadataCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RetrieveMetadataCompleted(Me, New RetrieveMetadataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5/RetrieveVersionMetadat"& _ 
            "a", RequestNamespace:="urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5", ResponseNamespace:="urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RetrieveVersionMetadata(ByRef psAuthContext As String, ByVal pasLogicalIds() As String, ByVal psVersion As String, ByVal psXMLRequestedMetadata As String, ByRef psOutXMLObjList As String) As String
            Dim results() As Object = Me.Invoke("RetrieveVersionMetadata", New Object() {psAuthContext, pasLogicalIds, psVersion, psXMLRequestedMetadata, psOutXMLObjList})
            psAuthContext = CType(results(1),String)
            psOutXMLObjList = CType(results(2),String)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RetrieveVersionMetadataAsync(ByVal psAuthContext As String, ByVal pasLogicalIds() As String, ByVal psVersion As String, ByVal psXMLRequestedMetadata As String, ByVal psOutXMLObjList As String)
            Me.RetrieveVersionMetadataAsync(psAuthContext, pasLogicalIds, psVersion, psXMLRequestedMetadata, psOutXMLObjList, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RetrieveVersionMetadataAsync(ByVal psAuthContext As String, ByVal pasLogicalIds() As String, ByVal psVersion As String, ByVal psXMLRequestedMetadata As String, ByVal psOutXMLObjList As String, ByVal userState As Object)
            If (Me.RetrieveVersionMetadataOperationCompleted Is Nothing) Then
                Me.RetrieveVersionMetadataOperationCompleted = AddressOf Me.OnRetrieveVersionMetadataOperationCompleted
            End If
            Me.InvokeAsync("RetrieveVersionMetadata", New Object() {psAuthContext, pasLogicalIds, psVersion, psXMLRequestedMetadata, psOutXMLObjList}, Me.RetrieveVersionMetadataOperationCompleted, userState)
        End Sub
        
        Private Sub OnRetrieveVersionMetadataOperationCompleted(ByVal arg As Object)
            If (Not (Me.RetrieveVersionMetadataCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RetrieveVersionMetadataCompleted(Me, New RetrieveVersionMetadataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5/RetrieveMetadataByIshL"& _ 
            "ngRefs", RequestNamespace:="urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5", ResponseNamespace:="urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RetrieveMetadataByIshLngRefs(ByRef psAuthContext As String, ByVal palLngRefs() As Long, ByVal psXMLRequestedMetadata As String, ByRef psOutXMLObjList As String) As String
            Dim results() As Object = Me.Invoke("RetrieveMetadataByIshLngRefs", New Object() {psAuthContext, palLngRefs, psXMLRequestedMetadata, psOutXMLObjList})
            psAuthContext = CType(results(1),String)
            psOutXMLObjList = CType(results(2),String)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RetrieveMetadataByIshLngRefsAsync(ByVal psAuthContext As String, ByVal palLngRefs() As Long, ByVal psXMLRequestedMetadata As String, ByVal psOutXMLObjList As String)
            Me.RetrieveMetadataByIshLngRefsAsync(psAuthContext, palLngRefs, psXMLRequestedMetadata, psOutXMLObjList, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RetrieveMetadataByIshLngRefsAsync(ByVal psAuthContext As String, ByVal palLngRefs() As Long, ByVal psXMLRequestedMetadata As String, ByVal psOutXMLObjList As String, ByVal userState As Object)
            If (Me.RetrieveMetadataByIshLngRefsOperationCompleted Is Nothing) Then
                Me.RetrieveMetadataByIshLngRefsOperationCompleted = AddressOf Me.OnRetrieveMetadataByIshLngRefsOperationCompleted
            End If
            Me.InvokeAsync("RetrieveMetadataByIshLngRefs", New Object() {psAuthContext, palLngRefs, psXMLRequestedMetadata, psOutXMLObjList}, Me.RetrieveMetadataByIshLngRefsOperationCompleted, userState)
        End Sub
        
        Private Sub OnRetrieveMetadataByIshLngRefsOperationCompleted(ByVal arg As Object)
            If (Not (Me.RetrieveMetadataByIshLngRefsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RetrieveMetadataByIshLngRefsCompleted(Me, New RetrieveMetadataByIshLngRefsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5/GetDataObjectInfoByIsh"& _ 
            "LngRef", RequestNamespace:="urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5", ResponseNamespace:="urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetDataObjectInfoByIshLngRef(ByRef psAuthContext As String, ByVal plLngRef As Long, ByRef psOutXMLIshDataObjects As String) As String
            Dim results() As Object = Me.Invoke("GetDataObjectInfoByIshLngRef", New Object() {psAuthContext, plLngRef, psOutXMLIshDataObjects})
            psAuthContext = CType(results(1),String)
            psOutXMLIshDataObjects = CType(results(2),String)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetDataObjectInfoByIshLngRefAsync(ByVal psAuthContext As String, ByVal plLngRef As Long, ByVal psOutXMLIshDataObjects As String)
            Me.GetDataObjectInfoByIshLngRefAsync(psAuthContext, plLngRef, psOutXMLIshDataObjects, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetDataObjectInfoByIshLngRefAsync(ByVal psAuthContext As String, ByVal plLngRef As Long, ByVal psOutXMLIshDataObjects As String, ByVal userState As Object)
            If (Me.GetDataObjectInfoByIshLngRefOperationCompleted Is Nothing) Then
                Me.GetDataObjectInfoByIshLngRefOperationCompleted = AddressOf Me.OnGetDataObjectInfoByIshLngRefOperationCompleted
            End If
            Me.InvokeAsync("GetDataObjectInfoByIshLngRef", New Object() {psAuthContext, plLngRef, psOutXMLIshDataObjects}, Me.GetDataObjectInfoByIshLngRefOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetDataObjectInfoByIshLngRefOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetDataObjectInfoByIshLngRefCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetDataObjectInfoByIshLngRefCompleted(Me, New GetDataObjectInfoByIshLngRefCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5/GetNextDataObjectChunk"& _ 
            "ByIshLngRef", RequestNamespace:="urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5", ResponseNamespace:="urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetNextDataObjectChunkByIshLngRef(ByRef psAuthContext As String, ByVal plLngRef As Long, ByVal psEdGUID As String, ByRef plOffSet As Long, ByRef piSize As Integer, <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByRef pbOutBytes() As Byte) As String
            Dim results() As Object = Me.Invoke("GetNextDataObjectChunkByIshLngRef", New Object() {psAuthContext, plLngRef, psEdGUID, plOffSet, piSize, pbOutBytes})
            psAuthContext = CType(results(1),String)
            plOffSet = CType(results(2),Long)
            piSize = CType(results(3),Integer)
            pbOutBytes = CType(results(4),Byte())
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetNextDataObjectChunkByIshLngRefAsync(ByVal psAuthContext As String, ByVal plLngRef As Long, ByVal psEdGUID As String, ByVal plOffSet As Long, ByVal piSize As Integer, ByVal pbOutBytes() As Byte)
            Me.GetNextDataObjectChunkByIshLngRefAsync(psAuthContext, plLngRef, psEdGUID, plOffSet, piSize, pbOutBytes, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetNextDataObjectChunkByIshLngRefAsync(ByVal psAuthContext As String, ByVal plLngRef As Long, ByVal psEdGUID As String, ByVal plOffSet As Long, ByVal piSize As Integer, ByVal pbOutBytes() As Byte, ByVal userState As Object)
            If (Me.GetNextDataObjectChunkByIshLngRefOperationCompleted Is Nothing) Then
                Me.GetNextDataObjectChunkByIshLngRefOperationCompleted = AddressOf Me.OnGetNextDataObjectChunkByIshLngRefOperationCompleted
            End If
            Me.InvokeAsync("GetNextDataObjectChunkByIshLngRef", New Object() {psAuthContext, plLngRef, psEdGUID, plOffSet, piSize, pbOutBytes}, Me.GetNextDataObjectChunkByIshLngRefOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetNextDataObjectChunkByIshLngRefOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetNextDataObjectChunkByIshLngRefCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetNextDataObjectChunkByIshLngRefCompleted(Me, New GetNextDataObjectChunkByIshLngRefCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5/FolderLocation", RequestNamespace:="urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5", ResponseNamespace:="urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function FolderLocation(ByRef psAuthContext As String, ByVal psLogicalId As String, ByRef peOutBaseFolder As eBaseFolder, ByRef pasOutFolderPath() As String, ByRef palOutFolderRefs() As Long) As String
            Dim results() As Object = Me.Invoke("FolderLocation", New Object() {psAuthContext, psLogicalId, peOutBaseFolder, pasOutFolderPath, palOutFolderRefs})
            psAuthContext = CType(results(1),String)
            peOutBaseFolder = CType(results(2),eBaseFolder)
            pasOutFolderPath = CType(results(3),String())
            palOutFolderRefs = CType(results(4),Long())
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub FolderLocationAsync(ByVal psAuthContext As String, ByVal psLogicalId As String, ByVal peOutBaseFolder As eBaseFolder, ByVal pasOutFolderPath() As String, ByVal palOutFolderRefs() As Long)
            Me.FolderLocationAsync(psAuthContext, psLogicalId, peOutBaseFolder, pasOutFolderPath, palOutFolderRefs, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub FolderLocationAsync(ByVal psAuthContext As String, ByVal psLogicalId As String, ByVal peOutBaseFolder As eBaseFolder, ByVal pasOutFolderPath() As String, ByVal palOutFolderRefs() As Long, ByVal userState As Object)
            If (Me.FolderLocationOperationCompleted Is Nothing) Then
                Me.FolderLocationOperationCompleted = AddressOf Me.OnFolderLocationOperationCompleted
            End If
            Me.InvokeAsync("FolderLocation", New Object() {psAuthContext, psLogicalId, peOutBaseFolder, pasOutFolderPath, palOutFolderRefs}, Me.FolderLocationOperationCompleted, userState)
        End Sub
        
        Private Sub OnFolderLocationOperationCompleted(ByVal arg As Object)
            If (Not (Me.FolderLocationCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent FolderLocationCompleted(Me, New FolderLocationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5/Containing", RequestNamespace:="urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5", ResponseNamespace:="urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Containing(ByRef psAuthContext As String, ByVal psLogicalId As String, ByVal psVersionNumber As String, ByVal psXMLRequestedMetaData As String, ByRef psOutXMLObjList As String) As String
            Dim results() As Object = Me.Invoke("Containing", New Object() {psAuthContext, psLogicalId, psVersionNumber, psXMLRequestedMetaData, psOutXMLObjList})
            psAuthContext = CType(results(1),String)
            psOutXMLObjList = CType(results(2),String)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ContainingAsync(ByVal psAuthContext As String, ByVal psLogicalId As String, ByVal psVersionNumber As String, ByVal psXMLRequestedMetaData As String, ByVal psOutXMLObjList As String)
            Me.ContainingAsync(psAuthContext, psLogicalId, psVersionNumber, psXMLRequestedMetaData, psOutXMLObjList, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ContainingAsync(ByVal psAuthContext As String, ByVal psLogicalId As String, ByVal psVersionNumber As String, ByVal psXMLRequestedMetaData As String, ByVal psOutXMLObjList As String, ByVal userState As Object)
            If (Me.ContainingOperationCompleted Is Nothing) Then
                Me.ContainingOperationCompleted = AddressOf Me.OnContainingOperationCompleted
            End If
            Me.InvokeAsync("Containing", New Object() {psAuthContext, psLogicalId, psVersionNumber, psXMLRequestedMetaData, psOutXMLObjList}, Me.ContainingOperationCompleted, userState)
        End Sub
        
        Private Sub OnContainingOperationCompleted(ByVal arg As Object)
            If (Not (Me.ContainingCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ContainingCompleted(Me, New ContainingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5/UsingBaseline", RequestNamespace:="urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5", ResponseNamespace:="urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function UsingBaseline(ByRef psAuthContext As String, ByVal psBaselineId As String, ByVal psXMLRequestedMetaData As String, ByRef psOutXMLObjList As String) As String
            Dim results() As Object = Me.Invoke("UsingBaseline", New Object() {psAuthContext, psBaselineId, psXMLRequestedMetaData, psOutXMLObjList})
            psAuthContext = CType(results(1),String)
            psOutXMLObjList = CType(results(2),String)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub UsingBaselineAsync(ByVal psAuthContext As String, ByVal psBaselineId As String, ByVal psXMLRequestedMetaData As String, ByVal psOutXMLObjList As String)
            Me.UsingBaselineAsync(psAuthContext, psBaselineId, psXMLRequestedMetaData, psOutXMLObjList, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UsingBaselineAsync(ByVal psAuthContext As String, ByVal psBaselineId As String, ByVal psXMLRequestedMetaData As String, ByVal psOutXMLObjList As String, ByVal userState As Object)
            If (Me.UsingBaselineOperationCompleted Is Nothing) Then
                Me.UsingBaselineOperationCompleted = AddressOf Me.OnUsingBaselineOperationCompleted
            End If
            Me.InvokeAsync("UsingBaseline", New Object() {psAuthContext, psBaselineId, psXMLRequestedMetaData, psOutXMLObjList}, Me.UsingBaselineOperationCompleted, userState)
        End Sub
        
        Private Sub OnUsingBaselineOperationCompleted(ByVal arg As Object)
            If (Not (Me.UsingBaselineCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UsingBaselineCompleted(Me, New UsingBaselineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5")>  _
    Public Enum eISHStatusgroup
        
        '''<remarks/>
        ISHReleasedStates
        
        '''<remarks/>
        ISHReleasedOrDraftStates
        
        '''<remarks/>
        ISHOutOfDateOrReleasedStates
        
        '''<remarks/>
        ISHNoStatusFilter
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:trisoft.be:WebServices:InfoShare:PublicationOutput:2.5")>  _
    Public Enum eBaseFolder
        
        '''<remarks/>
        Data
        
        '''<remarks/>
        System
        
        '''<remarks/>
        Favorites
        
        '''<remarks/>
        EditorTemplate
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub ReleaseCompletedEventHandler(ByVal sender As Object, ByVal e As ReleaseCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReleaseCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property psAuthContext() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property psOutXMLBaselineFreezeReport() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(2),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property pbOutIsFrozen() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(3),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub ReleaseByIshLngRefCompletedEventHandler(ByVal sender As Object, ByVal e As ReleaseByIshLngRefCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReleaseByIshLngRefCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property psAuthContext() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property psOutXMLBaselineFreezeReport() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(2),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property pbOutIsFrozen() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(3),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub GetMetaDataByIshLngRefCompletedEventHandler(ByVal sender As Object, ByVal e As GetMetaDataByIshLngRefCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetMetaDataByIshLngRefCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property psAuthContext() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property psOutXMLObjList() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(2),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub GetMetaDataCompletedEventHandler(ByVal sender As Object, ByVal e As GetMetaDataCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetMetaDataCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property psAuthContext() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property psVersion() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(2),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property psOutXMLObjList() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(3),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub FindCompletedEventHandler(ByVal sender As Object, ByVal e As FindCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class FindCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property psAuthContext() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property psOutXMLObjList() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(2),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub RetrieveMetadataCompletedEventHandler(ByVal sender As Object, ByVal e As RetrieveMetadataCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RetrieveMetadataCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property psAuthContext() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property psOutXMLObjList() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(2),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub RetrieveVersionMetadataCompletedEventHandler(ByVal sender As Object, ByVal e As RetrieveVersionMetadataCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RetrieveVersionMetadataCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property psAuthContext() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property psOutXMLObjList() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(2),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub RetrieveMetadataByIshLngRefsCompletedEventHandler(ByVal sender As Object, ByVal e As RetrieveMetadataByIshLngRefsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RetrieveMetadataByIshLngRefsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property psAuthContext() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property psOutXMLObjList() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(2),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub GetDataObjectInfoByIshLngRefCompletedEventHandler(ByVal sender As Object, ByVal e As GetDataObjectInfoByIshLngRefCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetDataObjectInfoByIshLngRefCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property psAuthContext() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property psOutXMLIshDataObjects() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(2),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub GetNextDataObjectChunkByIshLngRefCompletedEventHandler(ByVal sender As Object, ByVal e As GetNextDataObjectChunkByIshLngRefCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetNextDataObjectChunkByIshLngRefCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property psAuthContext() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property plOffSet() As Long
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(2),Long)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property piSize() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(3),Integer)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property pbOutBytes() As Byte()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(4),Byte())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub FolderLocationCompletedEventHandler(ByVal sender As Object, ByVal e As FolderLocationCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class FolderLocationCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property psAuthContext() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property peOutBaseFolder() As eBaseFolder
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(2),eBaseFolder)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property pasOutFolderPath() As String()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(3),String())
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property palOutFolderRefs() As Long()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(4),Long())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub ContainingCompletedEventHandler(ByVal sender As Object, ByVal e As ContainingCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ContainingCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property psAuthContext() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property psOutXMLObjList() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(2),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub UsingBaselineCompletedEventHandler(ByVal sender As Object, ByVal e As UsingBaselineCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class UsingBaselineCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property psAuthContext() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property psOutXMLObjList() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(2),String)
            End Get
        End Property
    End Class
End Namespace
